/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.util.Calendar;

/**
 *
 * @author Angel
 */
public class AgregarPago extends javax.swing.JDialog {

    /**
     * Creates new form AgregarPago
     */
    public int pac_id;
    int año, mes, dia;

    public AgregarPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Agregar Pago");
        this.setSize(650, 400);
        this.setLocationRelativeTo(null);
        FechaActual();
        cbx_mes.setSelectedIndex(mes);
        cbx_dia.setSelectedIndex(dia);
    }

    public void FechaActual() {
        Calendar CA = Calendar.getInstance();
        dia = CA.get(Calendar.DATE) - 1;
        mes = CA.get(Calendar.MONTH);
        año = CA.get(Calendar.YEAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pago = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_concepto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pac_id = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbx_mes = new javax.swing.JComboBox<>();
        cbx_dia = new javax.swing.JComboBox<>();
        cbx_año = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_pago);
        txt_pago.setBounds(140, 150, 140, 31);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Pago:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 100, 30);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Concepto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 210, 80, 30);

        txt_concepto.setColumns(20);
        txt_concepto.setRows(5);
        jScrollPane1.setViewportView(txt_concepto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 210, 320, 96);

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel3.setText("Numero de Cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 140, 20);

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 70, 20);

        txt_pac_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pac_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pac_id);
        txt_pac_id.setBounds(160, 40, 240, 30);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar);
        btn_aceptar.setBounds(190, 320, 71, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 320, 90, 23);

        cbx_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cbx_mes);
        cbx_mes.setBounds(230, 100, 80, 20);

        cbx_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbx_dia);
        cbx_dia.setBounds(330, 100, 56, 20);

        cbx_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001" }));
        cbx_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_añoActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_año);
        cbx_año.setBounds(140, 100, 80, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/535813fc9bbdd54.JPG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if (!txt_pago.getText().trim().equals("") && !txt_pago.getText().trim().equals("") && !txt_concepto.getText().trim().equals("")) {

            String id = txt_pac_id.getText();
            String pago = txt_pago.getText();

            String año = cbx_año.getSelectedItem().toString();
            int mes = cbx_mes.getSelectedIndex();
            mes = mes + 1;
            String dia = cbx_dia.getSelectedItem().toString();
            String fecha = año + "-" + mes + "-" + dia;
            String concepto = txt_concepto.getText();
            try {

                String consulta = "INSERT INTO " + Conexion.tblpagos
                        + " (pac_id, pag_monto, pag_concepto, pag_fecha) "
                        + " VALUES "
                        + "('" + id + "', '" + pago + "', '" + concepto + "', '" + fecha + "')";

                //obtener conexion:
                Connection conn = Conexion.getConnection();
                PreparedStatement query = conn.prepareStatement(consulta);
                int filas = query.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(null, filas + "Pago agregado");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR AL REGISTRAR PAGO");
                }
                /*//else */

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error con la conexion a la base de datos: \n " + e);
            }//catch
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos", "ERROR- DATO FALTANTE", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txt_pac_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pac_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pac_idActionPerformed

    private void cbx_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_añoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPago dialog = new AgregarPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JComboBox<String> cbx_año;
    private javax.swing.JComboBox<String> cbx_dia;
    private javax.swing.JComboBox<String> cbx_mes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_concepto;
    private javax.swing.JTextField txt_pac_id;
    private javax.swing.JTextField txt_pago;
    // End of variables declaration//GEN-END:variables
}
