/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Angel
 */
public class AgregarPaciente extends javax.swing.JDialog {

    /**
     * Creates new form AgregarPaciente
     */
    public AgregarPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Pagina Principal");
        this.setSize(557, 317);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregarp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_domicilio = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_agregarp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_agregarp.setText("Agregar");
        btn_agregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarp);
        btn_agregarp.setBounds(180, 230, 110, 25);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Paciente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 180, 20);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Domicilio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 100, 90, 40);

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 160, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 230, 100, 25);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(200, 60, 300, 30);

        txt_domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_domicilioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_domicilio);
        txt_domicilio.setBounds(200, 110, 300, 30);
        getContentPane().add(txt_telefono);
        txt_telefono.setBounds(200, 160, 300, 30);

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        jLabel4.setText("Registrar Paciente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 0, 210, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/535813fc9bbdd54.JPG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 540, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarpActionPerformed
        // TODO add your handling code here:
        if (!txt_nombre.getText().trim().equals("")&& !txt_domicilio.getText().trim().equals("") && !txt_telefono.getText().trim().equals("")) {
            
        
        String nombre = txt_nombre.getText();
        String domicilio = txt_domicilio.getText();
        String telefono = txt_telefono.getText();

        try {
            

            String consulta = "INSERT INTO " + Conexion.tblpacientes
                    + " (pac_nombre, pac_direccion, pac_telefono) "
                    + " VALUES "
                    + "('" + nombre + "', '" + domicilio + "', '" + telefono + "')";

           

            //obtener conexion:
            Connection conn = Conexion.getConnection();
            PreparedStatement query = conn.prepareStatement(consulta,Statement.RETURN_GENERATED_KEYS);
            
            //int filas = query.executeUpdate();
            query.executeUpdate();
            ResultSet rs = query.getGeneratedKeys();
            
            int generatedKey = 0;
            if (rs.next()) {
                generatedKey = rs.getInt(1);
                JOptionPane.showMessageDialog(null," Paciente Agregado \n Numero de Cliente: "+generatedKey);
                
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo Agregar al Usuario");
            }
            /*//else */

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion a la base de datos: \n " + e);
        }//catch
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos","ERROR- DATO FALTANTE",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_agregarpActionPerformed

    private void txt_domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_domicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_domicilioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPaciente dialog = new AgregarPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_domicilio;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
