/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Angel
 */
public class BuscarPacientes extends javax.swing.JDialog {

    /**
     * Creates new form BuscarPacientes
     */
    public BuscarPacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setTitle("Pacientes");
        this.setSize(1185, 520);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_id);
        txt_id.setBounds(10, 46, 160, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Ver Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 200, 110, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 200, 110, 30);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel1.setText("Numero de cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 21, 180, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de Cliente", "Nombre", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 0, 910, 480);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 84, 170, 23);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(10, 109, 160, 30);

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir);
        btn_salir.setBounds(60, 290, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/535813fc9bbdd54.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 860, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();
        String nombre = txt_nombre.getText();
        String consulta = "SELECT * FROM " + Conexion.tblpacientes;
        int quitarand = 0; //bandera

        if (!id.equals("") || !nombre.equals("")) {
            consulta += " WHERE ";
            quitarand = 1;
        }//if

        if (!id.equals("")) {
            consulta += " pac_id=" + id + " AND";
        }
        if (!nombre.equals("")) {
            consulta += " pac_nombre LIKE'%" + nombre + "%' AND";
        }

        if (quitarand == 1) {
            consulta = consulta.substring(0, consulta.length() - 4);
        }//if
        TableColumnModel modelcol = jTable1.getColumnModel();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int total = modelcol.getColumnCount();
        modelo.setRowCount(0);

        try {
            Connection conn = Conexion.getConnection();

            //preparar:
            PreparedStatement query = conn.prepareStatement(consulta);
            ResultSet rs = query.executeQuery();

            //resultados
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));

                String idd = rs.getString("pac_id");
                String nombree = rs.getString("pac_nombre");
                modelo.addRow(v);
                jTable1.setModel(modelo);

            }//while
            for (int i = 0; i < total; i++) {
                int tail = 0;
                int total2 = modelo.getRowCount();
                for (int j = 0; j < total2; j++) {
                    if (modelo.getValueAt(j, i) != null) {
                        int tail2 = modelo.getValueAt(j, i).toString().length() * 7;
                        if (tail2 > tail) {
                            tail = tail2;
                        }
                        modelcol.getColumn(i).setPreferredWidth(tail);

                    }
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la busqueda: " + e);
        }//catch
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String consulta = "SELECT * FROM " + Conexion.tblpacientes;
        TableColumnModel modelcol = jTable1.getColumnModel();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int total = modelcol.getColumnCount();
        modelo.setRowCount(0);

        try {
            Connection conn = Conexion.getConnection();

            //preparar:
            PreparedStatement query = conn.prepareStatement(consulta);
            ResultSet rs = query.executeQuery();

            String resultados_impresos = "";

            //resultados
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                modelo.addRow(v);
                jTable1.setModel(modelo);

            }//while
            for (int i = 0; i < total; i++) {
                int tail = 0;
                int total2 = modelo.getRowCount();
                for (int j = 0; j < total2; j++) {
                    if (modelo.getValueAt(j, i) != null) {
                        int tail2 = modelo.getValueAt(j, i).toString().length() * 7;
                        if (tail2 > tail) {
                            tail = tail2;
                        }
                        modelcol.getColumn(i).setPreferredWidth(tail);

                    }
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la busqueda: " + e);
        }//catch
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarPacientes dialog = new BuscarPacientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
