/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import Conexion.Conexion;
import FechaActual.FechaActual;

/**
 *
 * @author Angel
 */
public class Cortes extends javax.swing.JDialog {

    /**
     * Creates new form Cortes
     */
    public Cortes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Cortes");
        this.setSize(945,520);
        this.setLocationRelativeTo(null);
        FechaActual FA = new FechaActual();
        FA.generarFechaDia();
        txt_fecha.setText(FA.fechaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_fecha = new javax.swing.JLabel();
        btn_dia = new javax.swing.JButton();
        btn_mes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_monto_dia = new javax.swing.JLabel();
        lb_monto_mes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero paciente", "Monto", "Concepto", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 0, 660, 490);

        txt_fecha.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        getContentPane().add(txt_fecha);
        txt_fecha.setBounds(0, 0, 100, 30);

        btn_dia.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btn_dia.setText("Hacer corte del día");
        btn_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dia);
        btn_dia.setBounds(10, 90, 200, 40);

        btn_mes.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btn_mes.setText("Hacer corte del mes");
        btn_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mes);
        btn_mes.setBounds(10, 170, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ventas del Día: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 280, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ventas del Mes:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 330, 120, 20);

        lb_monto_dia.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        lb_monto_dia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lb_monto_dia);
        lb_monto_dia.setBounds(160, 270, 140, 30);

        lb_monto_mes.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        lb_monto_mes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lb_monto_mes);
        lb_monto_mes.setBounds(160, 330, 140, 30);

        jButton1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 430, 110, 30);

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel5.setText("CORTES.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 0, 180, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clock_ballonicon2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 40, 140, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/535813fc9bbdd54.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesActionPerformed
        // TODO add your handling code here:
        FechaActual FD = new FechaActual();
        FD.generarFechaMes();
        llenarTabla(FD.fechaMes);
        lb_monto_mes.setText("$" +total(FD.fechaMes));
    }//GEN-LAST:event_btn_mesActionPerformed

    private void btn_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diaActionPerformed
        // TODO add your handling code here:
        FechaActual FD = new FechaActual();
        FD.generarFechaDia();
        llenarTabla(FD.fechaActual);
        
        
        lb_monto_dia.setText("$"+total(FD.fechaActual));
    }//GEN-LAST:event_btn_diaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public String total(String x){
        String consulta = "SELECT SUM(pag_monto) Corte FROM `pagos` WHERE pag_fecha LIKE '%"+x+"%'";
        String total="";
        try {
            Connection conn = Conexion.getConnection();

            //preparar:
            PreparedStatement query = conn.prepareStatement(consulta);
            ResultSet rs = query.executeQuery();
            
            //resultados
            while (rs.next()) {

                 total = rs.getString("Corte");
                //String nombre = rs.getString("pac_nombre");
                
               
            }//while

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la busqueda: " + e);
        }//catch
        return total;
    }
    public void llenarTabla(String x) {
        //instanciar metodo de fecha actual;
        String consulta = "SELECT pac_id, pag_monto, pag_concepto, pag_fecha FROM pagos WHERE pag_fecha LIKE '%"+x+"%'";
        
        TableColumnModel modelcol = jTable1.getColumnModel();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int total = modelcol.getColumnCount();

        modelo.setRowCount(0);
        
        try {
            Connection conn = Conexion.getConnection();

            //preparar:
            PreparedStatement query = conn.prepareStatement(consulta);
            ResultSet rs = query.executeQuery();

      

            //resultados
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                /*String id = rs.getString("pac_id");
                String nombre = rs.getString("pac_nombre");
                */
                modelo.addRow(v);
                jTable1.setModel(modelo);
            }//while

            for (int i = 0; i < total; i++) {
                int tail = 0;
                int total2 = modelo.getRowCount();
                for (int j = 0; j < total2; j++) {
                    if (modelo.getValueAt(j, i) != null) {
                        int tail2 = modelo.getValueAt(j, i).toString().length() * 7;
                        if (tail2 > tail) {
                            tail = tail2;
                        }
                        modelcol.getColumn(i).setPreferredWidth(tail);

                    }
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la busqueda: " + e);
        }//catch
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cortes dialog = new Cortes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dia;
    private javax.swing.JButton btn_mes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_monto_dia;
    private javax.swing.JLabel lb_monto_mes;
    private javax.swing.JLabel txt_fecha;
    // End of variables declaration//GEN-END:variables
}
